version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-depdencies-
      - run: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies={{ checksum "yarn.lock" }}
      - run: yarn build
  deploy:
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
